name: Hola Mundo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    hola_mundo:
        runs-on: ubuntu-latest
        steps:
            - name: Saludo
              run: echo "Hola Mundo"