name: Hola Mundo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    hola_mundo:
        runs-on: ubuntu-latest
        steps:
            - name: Saludo
              run: echo "Hola Mundo"
            - name: Fecha y hora
              run: date
            - name: Usuario
              run: whoami
            - name: Mostrar directorio
              run: pwd
            - name: Listar archivos
              run: ls -la